logging:
  file:
    name: logs/api.log
    max-size: 500MB
    max-history: 1
  level:
    root: info
    org.msa.item: debug

spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  instance:
    hostname: eureka-server
  client:
    serverUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "*"