# Logging Configuration
logging:
  file:
    name: logs/api-local.log
    max-size: 500MB
    max-history: 1
  level:
    root: info
    org.msa.item: debug

# Spring Datasource Configuration
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/msa
    username: hoowave
    password:

  # JPA and Hibernate Configuration
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        bytecode:
          format_sql: true

# Springdoc Configuration
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka